[package]
name = "sedum"
version = "0.0.1"
authors = ["azusachino <azusachino@duck.com>"]
edition = "2021"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/azusachino/sedum"

[dependencies]
anyhow = "1.0"
axum = "0.6"
chrono = "0.4"

# possible features: json, cluster, tokio-rustls-comp
redis = { version = "0.23", features = ["tokio-comp"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

sqlx = { version = "0.6", features = [
    "chrono",
    "postgres",
    "runtime-tokio-rustls",
] }

thiserror = "1.0"
tokio = { version = "1.28", features = ["full"] }
# for logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }